kind: pipeline
type: docker
name: Android app

steps:
  - name: build app
    image: ghcr.io/cirruslabs/flutter:stable
    environment:
      ANDROID_KEY_FILE: /tmp/key.properties
    commands:
      - wget http://100.122.131.70:5000/fsdownload/EzGoaL9oR/service-account.json -O /tmp/service-account.json
      - wget http://100.122.131.70:5000/fsdownload/geNamyUzD/key.properties -O /tmp/key.properties
      - wget http://100.122.131.70:5000/fsdownload/UkWzFqNmc/keystore.jks -O /tmp/keystore.jks
      - flutter doctor
      - flutter pub get
      - flutter pub run flutter_native_splash:create
      - flutter build apk --split-per-abi
      - flutter build apk
#  - name: git hub release
#    environment:
#      KEYCHAIN_PASS:
#        from_secret: keychain_pass
#      PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/gz/dev/flutter/bin"
#    commands:
#      - source /Users/gz/.zshrc
#      - gh release upload ${DRONE_TAG} build/app/outputs/flutter-apk/* -R lamarios/clipious
#    when:
#      event: tag
#  - name: Release Android
#    environment:
#      KEYCHAIN_PASS:
#        from_secret: keychain_pass
#      PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/gz/dev/flutter/bin"
#    commands:
#      - source /Users/gz/.zshrc
#      - flutter doctor
#      - security unlock-keychain -p $${KEYCHAIN_PASS} /Users/gz/Library/Keychains/login.keychain-db
#      - flutter build appbundle
#      - cd android
#      - fastlane deploy
#    when:
#      event: tag
trigger:
  event:
    - push
    - tag
