kind: pipeline
type: docker
name: Android app

steps:
  - name: build app
    image: ghcr.io/cirruslabs/flutter:stable
    environment:
      ANDROID_KEY_FILE: /tmp/key.properties
      SERVER_URL:
        from_secret: server_url
    commands:
      - wget http://$SERVER_URL/service-account.json -O /tmp/service-account.json
      - wget http://$SERVER_URL/key.properties -O /tmp/key.properties
      - wget http://$SERVER_URL/keystore.jks -O /tmp/keystore.jks
      - flutter doctor
      - flutter pub get
      - flutter pub run flutter_native_splash:create
      - flutter build apk --split-per-abi
      - flutter build apk
      - flutter build appbundle
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: "build/app/outputs/flutter-apk/*.apk"
    when:
      event: tag
  - name: Release Android
    image: ruby
    environment:
      JSON_KEY_FILE: /tmp/service-account.json
      SERVER_URL:
        from_secret: server_url
    commands:
      - wget http://$SERVER_URL/service-account.json -O /tmp/service-account.json
      - wget http://$SERVER_URL/key.properties -O /tmp/key.properties
      - wget http://$SERVER_URL/keystore.jks -O /tmp/keystore.jks
      - cd android
      - gem install fastlane
      - fastlane deploy
    when:
      event: tag
trigger:
  event:
    - push
    - tag
